env:
  secure: HuMEH1MDVt0br36tMjkcpC520OIA+nWV5fACPSxUeRfB86lc+n3WDbsC1qC386QOv5hKREcREGTIGF591GY04ApUmQlWNJymk2JjAkVKO2Dp3/jtBeFPXDbQ+sOAkfgcTgoC2yRWOfAAj1nJi1hKw0sZAwLP2n3KMjGSCYN8zGw=
  global:
  - BROWSER_BINARY=/usr/bin/google-chrome
  - BROWSER="chrome"
  - SHOW_BROWSER="false"
git:
  submodules: false
language: node_js
node_js:
- 8.11.3
install:
- npm install
before_script:
- npm run build
script:
- npm run all-tests
notifications:
  slack:
    secure: kHQvp3HZL5GRY58XrGdRhZKtUvGrxgsAKMawYYNO4PA9NXlr5EYwbYBCrud1DNJs6kdEPK48ItSnsWXKoDZTS+g96b56t8vjHl2d98EN4WwvORj3g9NNiZ0SESL2LUwFa5vCxlnTbxfCQcfNpStGrwYZZ9DnIGTDuLO2EqZxvP0=
after_failure:
  - sleep 10
  - echo "--actual end of .travis script--"
